#
export QBO_APIBASE="https://${QBO_SANDBOX}quickbooks.api.intuit.com/v3"
export QBO_REALMID="9341457265789222"
export QBO_FORMAT=json
export QBO_SCOPE="com.intuit.quickbooks.accounting"
#
export QBO_CONNECT_SERVER="https://appcenter.intuit.com/connect/oauth2"
export QBO_TOKEN_SERVER="https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"
export QBO_CALLBACK="https://appserver.tarrantadvisors.com/cgi/qbo_oauth.cgi"
export QBO_CLIENT=""
export QBO_SECRET=""
export QBO_REFRESH_TOKEN=""
export QBO_ACCESS_TOKEN=""
