#
# Replace "???" values as required for your environment
#
export ADOBE_SHARD="na3"
export ADOBE_APIBASE="https://api.${ADOBE_SHARD}.adobesign.com/api/rest/v6"
export ADOBE_FORMAT=json
export ADOBE_SCOPE="agreement_read:account+agreement_write:account+agreement_send:account+library_read:account"
#
export ADOBE_CONNECT_SERVER="https://secure.${ADOBE_SHARD}.adobesign.com/public/oauth/v2"
export ADOBE_TOKEN_SERVER="https://api.${ADOBE_SHARD}.adobesign.com/oauth/v2/token"
export ADOBE_REFRESH_SERVER="https://api.${ADOBE_SHARD}.adobesign.com/oauth/v2/refresh"
export ADOBE_CALLBACK="https://appserver.tarrantadvisors.com/cgi/adobe_oauth.cgi"
export ADOBE_CLIENT=""
export ADOBE_SECRET=""
export ADOBE_REFRESH_TOKEN=""
export ADOBE_ACCESS_TOKEN=""
